FROM node:20-alpine
WORKDIR /app

COPY Diversos/Scripts/_extracted/bulario-api-main/bulario-api-main/package*.json ./
RUN npm ci --omit=dev

COPY Diversos/Scripts/_extracted/bulario-api-main/bulario-api-main/ ./

ENV ENVIRONMENT=dev
ENV PORT=5000
EXPOSE 5000

CMD ["node", "app.js"]
