import type { NavIconName } from '../components/NavIcon';

const SECTION_ICONS: Record<string, NavIconName> = {
  dashboard: 'dashboard',
  entrada: 'users',
  ambulatorio: 'calendar',
  'pronto-atendimento': 'siren',
  internacao: 'bed',
  cirurgia: 'scalpel',
  pep: 'clipboard',
  enfermagem: 'stethoscope',
  ccih: 'shield',
  'alta-clinica': 'activity',
  fechamento: 'wallet',
  guias: 'file-text',
  comunicacao: 'mail',
  saida: 'lock',
  financeiro: 'wallet',
  suprimentos: 'boxes',
  rh: 'briefcase',
  'eng-clinica': 'wrench',
  farmacia: 'pill',
  laboratorio: 'flask',
  imagem: 'scan',
  sangue: 'blood',
  nutricao: 'utensils',
  oncologia: 'heart-pulse',
  operacional: 'building',
  gestao: 'bar-chart',
  relatorios: 'file-text',
  qualidade: 'ribbon',
  automacao: 'sparkles',
  configuracoes: 'wrench',
  'seguranca-lgpd': 'lock',
  'acesso-infra': 'lock',
  'integracoes-gov': 'plug',
  integracoes: 'plug',
  // legado (rotas antigas / breadcrumbs)
  atendimento: 'heart-pulse',
  pacientes: 'users',
  agenda: 'calendar',
  almoxarifado: 'boxes',
  compras: 'cart',
  faturamento: 'wallet',
  bi: 'bar-chart',
  regulacao: 'activity',
  'acesso-fisico': 'lock',
};

const BRANCH_ICONS: Record<string, NavIconName> = {
  'ent-portaria': 'lock',
  'ent-cadastro': 'users',
  'ent-reg': 'activity',
  ps: 'siren',
  amb: 'calendar',
  int: 'bed',
  uti: 'activity',
  cc: 'scalpel',
  'enf-sae': 'clipboard',
  'enf-assist': 'stethoscope',
  'fec-aud': 'clipboard',
  'fec-sus': 'building',
  'fec-conv': 'wallet',
  'fec-part': 'wallet',
  'gestao': 'file-text',
  'tiss': 'wallet',
  'funi': 'file-text',
  'sus': 'building',
  'fluxos': 'clipboard',
  'correio': 'mail',
  'colaboracao': 'users',
  'canais': 'plug',
  'fin-rec': 'wallet',
  'fin-pag': 'wallet',
  'fin-tes': 'wallet',
  'fin-fisc': 'file-text',
  'sup-almox': 'boxes',
  'sup-comp': 'cart',
  'gest-bi': 'bar-chart',
  'rel-assist': 'heart-pulse',
  'rel-op': 'activity',
  'rel-fin': 'wallet',
  'rel-conv': 'wallet',
  'rel-far': 'pill',
  'rel-alm': 'boxes',
  'rel-rh': 'briefcase',
  'rel-qual': 'ribbon',
  'op-hotel': 'shirt',
  'op-transp': 'ambulance',
  'acf-patrim': 'building',
  'pac-cad': 'users',
  'pac-rec': 'calendar',
  'pac-pep-links': 'clipboard',
  'fat-sus': 'building',
  'fat-conv': 'wallet',
  'fat-part': 'wallet',
  'fat-aud': 'clipboard',
  'bi-assist': 'heart-pulse',
  'bi-fin': 'bar-chart',
  'bi-op': 'activity',
};

const INTEGRACAO_LEAF_IDS = new Set([
  'int-tiss', 'int-ans', 'int-cnes', 'int-cadsus', 'int-sisreg', 'int-esus',
  'int-hl7', 'int-fhir', 'int-pacs', 'int-lab', 'int-painel', 'int-ia', 'int-tele',
]);

const LEAF_ICONS: Record<string, NavIconName> = {
  'dash-visao': 'dashboard',
  'dash-assistencial': 'heart-pulse',
  'dash-indicadores': 'bar-chart',
  'dash-alertas': 'bell',
  'dash-tarefas': 'clipboard',
  'dash-agenda': 'calendar',
  'pep-evol-med': 'stethoscope',
  'pep-evol-enf': 'stethoscope',
  'pep-evol-multi': 'users',
  'pep-presc': 'pill',
  'pep-cid': 'clipboard',
  'pep-sv': 'activity',
  'pep-assin': 'lock',
  'seg-dash': 'shield',
  'seg-aud': 'clipboard',
  'seg-cons': 'lock',
  'seg-tit': 'users',
  'seg-inc': 'siren',
  'seg-mfa': 'lock',
  'gov-painel': 'plug',
  'gov-cns': 'users',
  'gov-cnes': 'building',
  'gov-sih': 'file-text',
  'gov-sia': 'file-text',
  'gov-tiss': 'wallet',
  'gov-fhir': 'plug',
  'gov-rnds': 'activity',
  'int-connect': 'plug',
  'conn-inbox': 'mail',
  'conn-enviadas': 'mail',
  'conn-rascunhos': 'clipboard',
  'conn-chat': 'users',
  'conn-notificacoes': 'bell',
  'conn-mural': 'clipboard',
  'conn-chamados': 'clipboard',
  'conn-tarefas': 'clipboard',
  'conn-aprovacoes': 'clipboard',
  'conn-agenda': 'calendar',
  'conn-whatsapp': 'plug',
  'int-ia': 'sparkles',
  'int-tele': 'video',
  'int-tiss': 'wallet',
  'int-ans': 'shield',
  'int-cnes': 'building',
  'int-cadsus': 'users',
  'int-sisreg': 'calendar',
  'int-esus': 'clipboard',
  'int-hl7': 'plug',
  'int-fhir': 'plug',
  'int-pacs': 'scan',
  'int-lab': 'flask',
  'int-painel': 'dashboard',
  'auto-ia': 'sparkles',
  'auto-bar': 'scan',
  'auto-rfid': 'activity',
  'auto-fluxos': 'sparkles',
  'cfg-regras': 'clipboard',
  'cfg-param': 'wrench',
  'cfg-int': 'plug',
  'rh-users': 'users',
  'rh-colab': 'users',
  'rh-prof': 'stethoscope',
  'op-h-noc': 'activity',
  'op-h-hig': 'shirt',
  'op-tr-painel': 'ambulance',
  'op-tr-fila': 'users',
  'op-tr-eq': 'package',
  'acf-portaria': 'users',
  'acf-park': 'parking',
  'acf-face': 'scan',
  'acf-cat': 'lock',
  'acf-totem': 'building',
  'acf-lpr': 'scan',
  'acf-mon': 'activity',
  'fat-dash': 'bar-chart',
  'guias-hub': 'file-text',
  'fat-tiss': 'wallet',
  'fat-funi-hub': 'file-text',
  'fat-guias': 'file-text',
  'fat-funi': 'file-text',
  'guias-tiss': 'wallet',
  'guias-sus': 'building',
  'guias-aut': 'clipboard',
  'guias-fat': 'wallet',
  'guias-aud': 'clipboard',
  'tiss-aut': 'clipboard',
  'tiss-lotes': 'package',
  'fat-glosa': 'clipboard',
  'rel-central': 'file-text',
  'comp-ped': 'cart',
};

const LEAF_PREFIX_ICONS: Array<[string, NavIconName]> = [
  ['ps-', 'siren'],
  ['amb-', 'calendar'],
  ['int-', 'bed'],
  ['cc-', 'scalpel'],
  ['uti-', 'activity'],
  ['pac-', 'users'],
  ['pep-', 'clipboard'],
  ['ag-', 'calendar'],
  ['enf-', 'stethoscope'],
  ['far-', 'pill'],
  ['alm-', 'boxes'],
  ['lab-', 'flask'],
  ['img-', 'scan'],
  ['bs-', 'blood'],
  ['nut-', 'utensils'],
  ['fat-', 'wallet'],
  ['guias-', 'file-text'],
  ['conn-', 'mail'],
  ['funi-', 'file-text'],
  ['fin-', 'wallet'],
  ['comp-', 'cart'],
  ['rh-', 'briefcase'],
  ['ccih-', 'shield'],
  ['seg-', 'shield'],
  ['qual-', 'ribbon'],
  ['reg-', 'activity'],
  ['ec-', 'wrench'],
  ['bi-', 'bar-chart'],
  ['rel-', 'file-text'],
  ['op-h-', 'shirt'],
  ['op-tr-', 'ambulance'],
  ['acf-', 'lock'],
  ['gov-', 'plug'],
  ['int-', 'plug'],
  ['auto-', 'sparkles'],
  ['cfg-', 'wrench'],
];

export function getSectionIcon(sectionId: string): NavIconName {
  return SECTION_ICONS[sectionId] ?? 'file-text';
}

export function getBranchIcon(branchId: string): NavIconName {
  return BRANCH_ICONS[branchId] ?? 'package';
}

export function getLeafIcon(leafId: string): NavIconName {
  if (LEAF_ICONS[leafId]) return LEAF_ICONS[leafId];
  if (INTEGRACAO_LEAF_IDS.has(leafId)) return 'plug';
  for (const [prefix, icon] of LEAF_PREFIX_ICONS) {
    if (leafId.startsWith(prefix)) return icon;
  }
  return 'file-text';
}
