using SistemaHospitalar.Domain.Enums;

namespace SistemaHospitalar.Application.DTOs.Catalog;

public record ProfessionalListDto(
    Guid Id,
    string FullName,
    string? Crm,
    string? CouncilUf,
    Guid SpecialtyId,
    string SpecialtyName,
    bool HasPhoto);

public record ProfessionalDetailDto(
    Guid Id,
    string FullName,
    string? SocialName,
    string? Crm,
    string? CouncilUf,
    string? Cpf,
    string? Rg,
    DateOnly? BirthDate,
    Gender Gender,
    string? Email,
    string? Phone,
    string? MobilePhone,
    string? AddressStreet,
    string? AddressNumber,
    string? AddressComplement,
    string? AddressNeighborhood,
    string? AddressCity,
    string? AddressState,
    string? AddressZipCode,
    string? Notes,
    string? PhotoData,
    Guid SpecialtyId,
    string SpecialtyName,
    bool IsActive,
    DateTime CreatedAt);

public record CreateProfessionalRequest(
    string FullName,
    string? SocialName,
    string? Crm,
    string? CouncilUf,
    string? Cpf,
    string? Rg,
    DateOnly? BirthDate,
    Gender Gender,
    string? Email,
    string? Phone,
    string? MobilePhone,
    string? AddressStreet,
    string? AddressNumber,
    string? AddressComplement,
    string? AddressNeighborhood,
    string? AddressCity,
    string? AddressState,
    string? AddressZipCode,
    string? Notes,
    string? PhotoData,
    Guid SpecialtyId);

public record UpdateProfessionalRequest(
    string FullName,
    string? SocialName,
    string? Crm,
    string? CouncilUf,
    string? Cpf,
    string? Rg,
    DateOnly? BirthDate,
    Gender Gender,
    string? Email,
    string? Phone,
    string? MobilePhone,
    string? AddressStreet,
    string? AddressNumber,
    string? AddressComplement,
    string? AddressNeighborhood,
    string? AddressCity,
    string? AddressState,
    string? AddressZipCode,
    string? Notes,
    string? PhotoData,
    Guid SpecialtyId,
    bool IsActive);
